### ISSUE TITLE
Ⓜ️  Morfeo V1 Roadmap

### ISSUE THREAD

**Issue by mauroerta** [morfeojs/morfeo#831]
## General

 - [ ] `createMorfeo` singleton to create the morfeo instance
 - [x] Remove from `spec` and `core` packages  any type/logic related to responsive styles or multi-theming and move them into the `web` packages (#816)
 - [x] Inline multi-theming (#816)
 - [x] Simplify multi-theming by allowing only light and dark modes (#816)
 - [ ] Add `colorsSchemas` to the theme (web package augmentation) in order to have custom resolutions (default `@media (preferred-color-scheme: ...)`
 - [ ] Default theme improvements for both `core` and `web` packages.

## Build Time

- [x] `morfeo.css`
- [x] `morfeo.component` (React)
- [x] morfeo CLI
- [ ] re-enable `classNamePrefix`, `emojis`, and `minify` configurations (`createMorfeo` singleton needs to be done first)

## Docs

- [ ] landing page
- [ ] build time APIs
- [ ] Advanced use cases

###  Examples

 - [ ] Global example scenario (#708)
 - [x] Make an example app with `next` (app router)
 - [ ] Make an example app with `remix`
 - [x] Make an example app with `react`
 - [ ] Make an example app with `astro`
 - [ ] Make an example app with `solid`
 - [ ] Make an example app with `qwick`
